version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  test:
    executor:
      name: android/android-docker
      tag: 2024.08.1-ndk
      resource-class: large
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - android/restore-gradle-cache
      - run:
          name: Install Go
          command: |
            curl -sSL https://go.dev/dl/go1.22.6.linux-amd64.tar.gz -o go.tar.gz
            sudo tar -C /usr/local -xzf go.tar.gz
            echo 'export PATH=$PATH:/usr/local/go/bin' >> "$BASH_ENV"
      - run:
          name: Run Build and Tests
          command: ./gradlew assembleDebug check --no-daemon
      - android/save-gradle-cache
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_artifacts:
          path: app/build/reports
          destination: reports

workflows:
  test:
    jobs:
      - test
