version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: shadowsocks/android-ndk-go
    environment:
      JVM_OPTS: -Xmx3500m
      GRADLE_OPTS: -Dorg.gradle.workers.max=1 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy="in-process"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - restore_cache:
          key: go-{{ checksum "app/src/main/go/v2ray-plugin/go.sum" }}
      - run:
          name: Run Build and Tests
          command: ./gradlew assembleDebug check
      - save_cache:
          paths:
          - ~/go
          key: go-{{ checksum "app/src/main/go/v2ray-plugin/go.sum" }}
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android/build-cache
          key: jars-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_artifacts:
          path: app/build/reports
          destination: reports
